// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/opctl/opctl/sdks/go/model"
	"github.com/opctl/opctl/sdks/go/node"
)

type FakeNode struct {
	AddAuthStub        func(context.Context, model.AddAuthReq) error
	addAuthMutex       sync.RWMutex
	addAuthArgsForCall []struct {
		arg1 context.Context
		arg2 model.AddAuthReq
	}
	addAuthReturns struct {
		result1 error
	}
	addAuthReturnsOnCall map[int]struct {
		result1 error
	}
	GetDataStub        func(context.Context, model.GetDataReq) (model.ReadSeekCloser, error)
	getDataMutex       sync.RWMutex
	getDataArgsForCall []struct {
		arg1 context.Context
		arg2 model.GetDataReq
	}
	getDataReturns struct {
		result1 model.ReadSeekCloser
		result2 error
	}
	getDataReturnsOnCall map[int]struct {
		result1 model.ReadSeekCloser
		result2 error
	}
	ListDescendantsStub        func(context.Context, model.ListDescendantsReq) ([]*model.DirEntry, error)
	listDescendantsMutex       sync.RWMutex
	listDescendantsArgsForCall []struct {
		arg1 context.Context
		arg2 model.ListDescendantsReq
	}
	listDescendantsReturns struct {
		result1 []*model.DirEntry
		result2 error
	}
	listDescendantsReturnsOnCall map[int]struct {
		result1 []*model.DirEntry
		result2 error
	}
	StartOpStub        func(context.Context, model.StartOpReq) (string, error)
	startOpMutex       sync.RWMutex
	startOpArgsForCall []struct {
		arg1 context.Context
		arg2 model.StartOpReq
	}
	startOpReturns struct {
		result1 string
		result2 error
	}
	startOpReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNode) AddAuth(arg1 context.Context, arg2 model.AddAuthReq) error {
	fake.addAuthMutex.Lock()
	ret, specificReturn := fake.addAuthReturnsOnCall[len(fake.addAuthArgsForCall)]
	fake.addAuthArgsForCall = append(fake.addAuthArgsForCall, struct {
		arg1 context.Context
		arg2 model.AddAuthReq
	}{arg1, arg2})
	fake.recordInvocation("AddAuth", []interface{}{arg1, arg2})
	fake.addAuthMutex.Unlock()
	if fake.AddAuthStub != nil {
		return fake.AddAuthStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.addAuthReturns
	return fakeReturns.result1
}

func (fake *FakeNode) AddAuthCallCount() int {
	fake.addAuthMutex.RLock()
	defer fake.addAuthMutex.RUnlock()
	return len(fake.addAuthArgsForCall)
}

func (fake *FakeNode) AddAuthCalls(stub func(context.Context, model.AddAuthReq) error) {
	fake.addAuthMutex.Lock()
	defer fake.addAuthMutex.Unlock()
	fake.AddAuthStub = stub
}

func (fake *FakeNode) AddAuthArgsForCall(i int) (context.Context, model.AddAuthReq) {
	fake.addAuthMutex.RLock()
	defer fake.addAuthMutex.RUnlock()
	argsForCall := fake.addAuthArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNode) AddAuthReturns(result1 error) {
	fake.addAuthMutex.Lock()
	defer fake.addAuthMutex.Unlock()
	fake.AddAuthStub = nil
	fake.addAuthReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNode) AddAuthReturnsOnCall(i int, result1 error) {
	fake.addAuthMutex.Lock()
	defer fake.addAuthMutex.Unlock()
	fake.AddAuthStub = nil
	if fake.addAuthReturnsOnCall == nil {
		fake.addAuthReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addAuthReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNode) GetData(arg1 context.Context, arg2 model.GetDataReq) (model.ReadSeekCloser, error) {
	fake.getDataMutex.Lock()
	ret, specificReturn := fake.getDataReturnsOnCall[len(fake.getDataArgsForCall)]
	fake.getDataArgsForCall = append(fake.getDataArgsForCall, struct {
		arg1 context.Context
		arg2 model.GetDataReq
	}{arg1, arg2})
	fake.recordInvocation("GetData", []interface{}{arg1, arg2})
	fake.getDataMutex.Unlock()
	if fake.GetDataStub != nil {
		return fake.GetDataStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getDataReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) GetDataCallCount() int {
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	return len(fake.getDataArgsForCall)
}

func (fake *FakeNode) GetDataCalls(stub func(context.Context, model.GetDataReq) (model.ReadSeekCloser, error)) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = stub
}

func (fake *FakeNode) GetDataArgsForCall(i int) (context.Context, model.GetDataReq) {
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	argsForCall := fake.getDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNode) GetDataReturns(result1 model.ReadSeekCloser, result2 error) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = nil
	fake.getDataReturns = struct {
		result1 model.ReadSeekCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) GetDataReturnsOnCall(i int, result1 model.ReadSeekCloser, result2 error) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = nil
	if fake.getDataReturnsOnCall == nil {
		fake.getDataReturnsOnCall = make(map[int]struct {
			result1 model.ReadSeekCloser
			result2 error
		})
	}
	fake.getDataReturnsOnCall[i] = struct {
		result1 model.ReadSeekCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) ListDescendants(arg1 context.Context, arg2 model.ListDescendantsReq) ([]*model.DirEntry, error) {
	fake.listDescendantsMutex.Lock()
	ret, specificReturn := fake.listDescendantsReturnsOnCall[len(fake.listDescendantsArgsForCall)]
	fake.listDescendantsArgsForCall = append(fake.listDescendantsArgsForCall, struct {
		arg1 context.Context
		arg2 model.ListDescendantsReq
	}{arg1, arg2})
	fake.recordInvocation("ListDescendants", []interface{}{arg1, arg2})
	fake.listDescendantsMutex.Unlock()
	if fake.ListDescendantsStub != nil {
		return fake.ListDescendantsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listDescendantsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) ListDescendantsCallCount() int {
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	return len(fake.listDescendantsArgsForCall)
}

func (fake *FakeNode) ListDescendantsCalls(stub func(context.Context, model.ListDescendantsReq) ([]*model.DirEntry, error)) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = stub
}

func (fake *FakeNode) ListDescendantsArgsForCall(i int) (context.Context, model.ListDescendantsReq) {
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	argsForCall := fake.listDescendantsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNode) ListDescendantsReturns(result1 []*model.DirEntry, result2 error) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = nil
	fake.listDescendantsReturns = struct {
		result1 []*model.DirEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) ListDescendantsReturnsOnCall(i int, result1 []*model.DirEntry, result2 error) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = nil
	if fake.listDescendantsReturnsOnCall == nil {
		fake.listDescendantsReturnsOnCall = make(map[int]struct {
			result1 []*model.DirEntry
			result2 error
		})
	}
	fake.listDescendantsReturnsOnCall[i] = struct {
		result1 []*model.DirEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) StartOp(arg1 context.Context, arg2 model.StartOpReq) (string, error) {
	fake.startOpMutex.Lock()
	ret, specificReturn := fake.startOpReturnsOnCall[len(fake.startOpArgsForCall)]
	fake.startOpArgsForCall = append(fake.startOpArgsForCall, struct {
		arg1 context.Context
		arg2 model.StartOpReq
	}{arg1, arg2})
	fake.recordInvocation("StartOp", []interface{}{arg1, arg2})
	fake.startOpMutex.Unlock()
	if fake.StartOpStub != nil {
		return fake.StartOpStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.startOpReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) StartOpCallCount() int {
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	return len(fake.startOpArgsForCall)
}

func (fake *FakeNode) StartOpCalls(stub func(context.Context, model.StartOpReq) (string, error)) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = stub
}

func (fake *FakeNode) StartOpArgsForCall(i int) (context.Context, model.StartOpReq) {
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	argsForCall := fake.startOpArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNode) StartOpReturns(result1 string, result2 error) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = nil
	fake.startOpReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) StartOpReturnsOnCall(i int, result1 string, result2 error) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = nil
	if fake.startOpReturnsOnCall == nil {
		fake.startOpReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.startOpReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addAuthMutex.RLock()
	defer fake.addAuthMutex.RUnlock()
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNode) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ node.Node = new(FakeNode)
